# Generated by Django 4.2.6 on 2023-10-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_basket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
